# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nathan McCord's blog
email: mccordnate@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
    Hi. I just started this so I'm not sure what will come out of it but at the very least you should know I enjoy Computer Science, Go, and Entrepreneurship. That's probably a good start.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nathanmccord.com" # the base hostname & protocol for your site
twitter_username: natemccord
github_username: mccordnate

# Build settings
markdown: kramdown
